### ISSUE TITLE
Link in index.php points to wrong page

### ISSUE THREAD

**Issue by rlorenzo** [gbateson/moodle-mod_englishcentral#11]
When generating the links to English Central modules in index.php the link generated is /mod/englishcentral.php
See https://github.com/gbateson/moodle-mod_englishcentral/blob/master/index.php#L70

But what it should be is /mod/englishcentral/view.php

The links are currently broken when viewing the index page.

**Comment by gbateson** [comment]
Thanks rlorenzo.
This issue is fixed now. Please update your copy of this plugin at the next convenient opportunity.
