### ISSUE TITLE
Undefined properties in classes/auth.php

### ISSUE THREAD

**Issue by mudrd8mz** [gbateson/moodle-mod_englishcentral#6]
When installing the plugin, the properties like partnerid are not set yet and I am offered the following screen:

![image](https://user-images.githubusercontent.com/85831/56276456-cdace600-6102-11e9-8fa8-691f6b0b57ee.png)

When I click the "EnglishCentral.com" I am redirected to a page mod/englishcentral/support.php with the following notices shown:
```
Notice: Undefined property: stdClass::$consumerkey in mod/englishcentral/classes/auth.php on line 71

Notice: Undefined property: stdClass::$consumersecret in mod/englishcentral/classes/auth.php on line 72

Notice: Undefined property: stdClass::$encryptedsecret in mod/englishcentral/classes/auth.php on line 73
```

**Comment by gbateson** [comment]
Thanks David. This issue is fixed now 👍
